#!/bin/sh
# Exécuté UNE SEULE FOIS par l'entrypoint postgres, au premier initdb du volume.
# Crée les rôles applicatifs et le schéma complet de la base lobbybot.
# Les données sont migrées séparément (scripts/migrate_sqlite_to_pg.py).
set -e

psql -v ON_ERROR_STOP=1 -U postgres -d lobbybot <<EOSQL
-- ── Rôles ────────────────────────────────────────────────────────────
-- lobbybot  : bot Discord + website (tous droits sur le schéma)
-- generator : fn_account_generator (limité à epic_accounts)
CREATE ROLE lobbybot  LOGIN PASSWORD '${LOBBYBOT_DB_PASSWORD}';
CREATE ROLE generator LOGIN PASSWORD '${GENERATOR_DB_PASSWORD}';

-- ── Schéma ───────────────────────────────────────────────────────────
CREATE TABLE epic_accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            TEXT UNIQUE NOT NULL,
    pseudo           TEXT,
    password_enc     TEXT,
    secret_id        TEXT,
    device_id        TEXT,
    account_id       TEXT,
    is_active        INTEGER DEFAULT 1,
    created_at       TIMESTAMPTZ DEFAULT now(),
    last_used_at     TIMESTAMPTZ,
    owner_discord_id TEXT
);
CREATE INDEX idx_epic_accounts_account_id ON epic_accounts (account_id);
CREATE INDEX idx_epic_accounts_owner      ON epic_accounts (owner_discord_id);

CREATE TABLE users (
    discord_id  TEXT PRIMARY KEY,
    epic_pseudo TEXT,
    device_id   TEXT,
    account_id  TEXT,
    secret      TEXT,
    language    TEXT DEFAULT 'en',
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE premium (
    discord_id TEXT PRIMARY KEY,
    source     TEXT NOT NULL,
    granted_at TEXT NOT NULL,
    expires_at TEXT
);

CREATE TABLE loadout_presets (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id TEXT NOT NULL,
    name       TEXT NOT NULL,
    outfit     TEXT,
    backpack   TEXT,
    pickaxe    TEXT,
    emote      TEXT,
    is_active  INTEGER NOT NULL DEFAULT 0,
    UNIQUE (discord_id, name)
);

CREATE TABLE dashboard_admins (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           TEXT UNIQUE NOT NULL,
    password_hash   TEXT NOT NULL,
    failed_attempts INTEGER DEFAULT 0,
    locked          INTEGER DEFAULT 0,
    created_at      TIMESTAMPTZ DEFAULT now(),
    -- Lien vers le compte Discord de l'admin : le dashboard filtre les bots
    -- par owner_discord_id de l'admin connecté.
    discord_id      TEXT,
    -- 1 = mot de passe temporaire : changement obligatoire au premier login
    must_change_password INTEGER DEFAULT 0
);

CREATE TABLE dashboard_config (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Admins du bot Discord (source de vérité ; ADMIN_IDS du .env reste un
-- fallback de secours si cette table est vide/injoignable).
CREATE TABLE admins (
    discord_id TEXT PRIMARY KEY,
    label      TEXT,
    added_at   TIMESTAMPTZ DEFAULT now()
);

-- Config par propriétaire de bots : chaque bot applique les réglages de SON
-- owner. L'ancien globalConfig (dashboard_config) sert de défaut.
CREATE TABLE owner_settings (
    owner_discord_id TEXT PRIMARY KEY,
    creator_code     TEXT,
    status           TEXT,
    join_msg         TEXT,
    add_msg          TEXT,
    updated_at       TIMESTAMPTZ DEFAULT now()
);

-- ── Droits ───────────────────────────────────────────────────────────
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public TO lobbybot;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lobbybot;
GRANT SELECT, INSERT, UPDATE ON epic_accounts TO generator;
GRANT USAGE, SELECT ON SEQUENCE epic_accounts_id_seq TO generator;
EOSQL
